# lol-data-analysis

#### This is a Data Analysis project on a League of Legends dataset from 2022 using professional games.

##### This is a second try at updating README.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
